name: JFrog Audit (SAST)

on:
  workflow_dispatch:

permissions:
  contents: read
  security-events: write
  id-token: write

jobs:
  sast:
    name: jf audit --sast
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup JFrog CLI
        uses: jfrog/setup-jfrog-cli@v5
        env:
          JF_URL: https://solenglatest.jfrog.io 
        with:
          oidc-provider-name: mikios-github-oidc 

      - name: Verify JFrog connection
        run: jf rt ping

      - name: Run jf audit (SAST only)
        run: |
          jf --version
          jf audit \
            --sast \
            --watches=mikios-sast-watch
